// "use client";
// import * as React from "react";
// import { Metadata, NextPage } from "next";
// import "./style.css";
// import { useSelectedLayoutSegment } from "next/navigation";
// interface IDashboardLayoutProps {
//   children: React.ReactNode;
// }

// export const metadata: Metadata = {
//   title: "Next.js",
// };
// const DashboardLayout: NextPage<IDashboardLayoutProps> = ({ children }) => {
//   const segment = useSelectedLayoutSegment();

//   console.log(segment, "SEGMENT");
//   return (
//     <div className="dashboard-layout">
//       <h4>Dashboard header : {segment}</h4>
//       <div>{children}</div>
//       <h4>Dashboard footer</h4>
//     </div>
//   );
// };

// export default DashboardLayout;

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
